server:
  port: 8000

spring:
  application:
    name: houzhidao
  datasource:
      name: test
      url: jdbc:mysql://39.106.200.100:3306/gpp?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: wbw
      password: WANGbowen0223.
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        maxLifetime: 1800000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
        maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 10000

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapper-locations:
    - classpath:mybatis/*.xml
  type-aliases-package:
    - com.hippie.houzhidao.domain
